import {
  EvaluationItem,
  HealthMetricDimension,
  ActivityDataPoint,
  PrivacyStats,
  ReportItem,
  AuditLogEvent,
} from "@/types/dashboard";

export const MOCK_AGENT_STATUS = {
  connected: true,
  name: "Verdix Agent (US-East Enclave)",
  enclaveId: "enclave-org-prod-01",
  version: "0.1.0",
  latencyMs: 12,
  policyEngine: "Differential Privacy & k-Anonymity (k>=10)",
  lastHeartbeat: "Just now",
  environment: "Bare-Metal Kubernetes (Airgapped VPC)",
  datasetsMounted: 4,
};

export const MOCK_TOP_METRICS = {
  datasetHealth: {
    value: "94.2%",
    label: "Overall health score",
    trend: "+2.4%",
    isPositive: true,
  },
  privacyStatus: {
    value: "ENFORCED",
    label: "Privacy Status",
    supportingText: "0 raw records transferred",
    isEnforced: true,
  },
  evaluations: {
    value: "24",
    label: "Evaluations",
    supportingText: "3 currently processing",
    totalThisMonth: 86,
  },
  anomaliesDetected: {
    value: "42",
    label: "Anomalies Detected",
    supportingText: "Across recent evaluations",
    resolved: 38,
  },
};

export const MOCK_HEALTH_DIMENSIONS_7D: HealthMetricDimension[] = [
  {
    name: "Completeness",
    score: 96.8,
    target: 95.0,
    description: "Ratio of non-null and fully populated feature attributes",
    status: "Optimal",
  },
  {
    name: "Consistency",
    score: 92.4,
    target: 90.0,
    description: "Cross-field schema rules and semantic relationship coherence",
    status: "Optimal",
  },
  {
    name: "Validity",
    score: 95.1,
    target: 92.0,
    description: "Conformance to domain constraints, datatypes, and range limits",
    status: "Optimal",
  },
  {
    name: "Uniqueness",
    score: 92.5,
    target: 90.0,
    description: "Zero accidental duplicates or repeated primary identifying hashes",
    status: "Optimal",
  },
];

export const MOCK_HEALTH_DIMENSIONS_30D: HealthMetricDimension[] = [
  {
    name: "Completeness",
    score: 95.2,
    target: 95.0,
    description: "Ratio of non-null and fully populated feature attributes",
    status: "Optimal",
  },
  {
    name: "Consistency",
    score: 90.8,
    target: 90.0,
    description: "Cross-field schema rules and semantic relationship coherence",
    status: "Optimal",
  },
  {
    name: "Validity",
    score: 93.9,
    target: 92.0,
    description: "Conformance to domain constraints, datatypes, and range limits",
    status: "Optimal",
  },
  {
    name: "Uniqueness",
    score: 91.0,
    target: 90.0,
    description: "Zero accidental duplicates or repeated primary identifying hashes",
    status: "Optimal",
  },
];

export const MOCK_HEALTH_DIMENSIONS_90D: HealthMetricDimension[] = [
  {
    name: "Completeness",
    score: 93.5,
    target: 95.0,
    description: "Ratio of non-null and fully populated feature attributes",
    status: "Attention",
  },
  {
    name: "Consistency",
    score: 89.2,
    target: 90.0,
    description: "Cross-field schema rules and semantic relationship coherence",
    status: "Attention",
  },
  {
    name: "Validity",
    score: 92.1,
    target: 92.0,
    description: "Conformance to domain constraints, datatypes, and range limits",
    status: "Optimal",
  },
  {
    name: "Uniqueness",
    score: 90.4,
    target: 90.0,
    description: "Zero accidental duplicates or repeated primary identifying hashes",
    status: "Optimal",
  },
];

export const MOCK_ACTIVITY_TIMELINE: ActivityDataPoint[] = [
  { day: "Mon", date: "Sep 10", evaluations: 3, metricsGenerated: 18, healthAverage: 93.1 },
  { day: "Tue", date: "Sep 11", evaluations: 5, metricsGenerated: 32, healthAverage: 94.0 },
  { day: "Wed", date: "Sep 12", evaluations: 2, metricsGenerated: 12, healthAverage: 92.8 },
  { day: "Thu", date: "Sep 13", evaluations: 6, metricsGenerated: 40, healthAverage: 95.2 },
  { day: "Fri", date: "Sep 14", evaluations: 4, metricsGenerated: 26, healthAverage: 94.8 },
  { day: "Sat", date: "Sep 15", evaluations: 1, metricsGenerated: 6, healthAverage: 94.0 },
  { day: "Sun", date: "Sep 16", evaluations: 3, metricsGenerated: 19, healthAverage: 94.2 },
];

export const MOCK_RECENT_EVALUATIONS: EvaluationItem[] = [
  {
    id: "eval-8921",
    name: "Student Records",
    datasetAlias: "student_data_v2",
    status: "Completed",
    healthScore: 94.2,
    privacyStatus: "Protected",
    date: "2026-09-16 15:42",
    recordsEvaluated: 142000,
    anomaliesCount: 8,
    duration: "4.2s",
    metricsComputed: 24,
  },
  {
    id: "eval-8920",
    name: "Employee Dataset",
    datasetAlias: "employee_records",
    status: "Processing",
    healthScore: null,
    privacyStatus: "Protected",
    date: "2026-09-16 16:15",
    recordsEvaluated: 48500,
    anomaliesCount: 0,
    duration: "In progress...",
    metricsComputed: 12,
  },
  {
    id: "eval-8919",
    name: "Survey Dataset",
    datasetAlias: "student_survey",
    status: "Completed",
    healthScore: 88.7,
    privacyStatus: "Protected",
    date: "2026-09-15 11:20",
    recordsEvaluated: 89000,
    anomaliesCount: 22,
    duration: "3.1s",
    metricsComputed: 18,
  },
  {
    id: "eval-8918",
    name: "Customer Dataset",
    datasetAlias: "customer_data",
    status: "Completed",
    healthScore: 91.4,
    privacyStatus: "Protected",
    date: "2026-09-14 18:05",
    recordsEvaluated: 320000,
    anomaliesCount: 12,
    duration: "8.6s",
    metricsComputed: 36,
  },
  {
    id: "eval-8917",
    name: "Financial Transactions",
    datasetAlias: "ledger_audit_q3",
    status: "Completed",
    healthScore: 97.1,
    privacyStatus: "Protected",
    date: "2026-09-13 09:30",
    recordsEvaluated: 750000,
    anomaliesCount: 3,
    duration: "14.2s",
    metricsComputed: 48,
  },
];

export const MOCK_PRIVACY_STATS: PrivacyStats = {
  enforcementStatus: "ACTIVE",
  rawRecordsTransferred: 0,
  protectedMetricsExported: 18,
  blockedExportAttempts: 3,
  policyViolations: 0,
  activeEpsilonBudget: 0.5,
  minKAnonymityThreshold: 10,
};

export const MOCK_REPORTS: ReportItem[] = [
  {
    id: "rep-001",
    title: "Quarterly Academic Integrity & Dataset Health",
    dataset: "student_data_v2",
    generatedDate: "Sep 16, 2026",
    healthScore: 94.2,
    qualityScore: 96.0,
    privacyScore: 100,
    anomaliesFound: 8,
    status: "Verified",
    summary:
      "All 142k records evaluated in-enclave. Completeness is optimal at 96.8%. Zero identifying attributes exposed.",
    author: "Verdix Agent US-East",
  },
  {
    id: "rep-002",
    title: "Annual HR Workforce Distribution Assessment",
    dataset: "employee_records_q2",
    generatedDate: "Sep 14, 2026",
    healthScore: 92.8,
    qualityScore: 93.4,
    privacyScore: 100,
    anomaliesFound: 14,
    status: "Verified",
    summary:
      "Demographic fairness and pay equity variance computed with differential privacy noise (epsilon=0.5). Zero raw salaries exported.",
    author: "Verdix Agent US-East",
  },
  {
    id: "rep-003",
    title: "Alumni Survey Sentiment & Validity Analysis",
    dataset: "student_survey",
    generatedDate: "Sep 12, 2026",
    healthScore: 88.7,
    qualityScore: 89.1,
    privacyScore: 100,
    anomaliesFound: 22,
    status: "Verified",
    summary:
      "22 categorical inconsistencies detected across non-mandatory feedback questions. Protected aggregate counts generated.",
    author: "Verdix Agent US-East",
  },
  {
    id: "rep-004",
    title: "Global Customer Demographics & Churn Forecast Quality",
    dataset: "customer_data",
    generatedDate: "Sep 10, 2026",
    healthScore: 91.4,
    qualityScore: 92.5,
    privacyScore: 100,
    anomaliesFound: 12,
    status: "Verified",
    summary:
      "Zero PII transferred. Correlation matrix and quantile buckets verified compliant with strict k-anonymity (k>=10).",
    author: "Verdix Agent EU-Central",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEvent[] = [
  {
    id: "aud-1094",
    timestamp: "2026-09-16 16:15:02 UTC",
    event: "Evaluation created",
    actor: "Admin (Console)",
    targetDataset: "employee_records",
    enclaveId: "enclave-org-prod-01",
    status: "INFO",
    details: "Evaluation spec #eval-8920 dispatched to local agent. Target columns: [department, tenure, rating].",
    sha256Proof: "0x8f2a...e91c",
  },
  {
    id: "aud-1093",
    timestamp: "2026-09-16 15:42:30 UTC",
    event: "Export approved",
    actor: "Privacy Guardrail",
    targetDataset: "student_data_v2",
    enclaveId: "enclave-org-prod-01",
    status: "SUCCESS",
    details: "Export of 24 aggregate statistical metrics approved. Zero raw records detected in payload.",
    sha256Proof: "0x3b7d...4a02",
  },
  {
    id: "aud-1092",
    timestamp: "2026-09-16 15:42:28 UTC",
    event: "Protected metrics generated",
    actor: "Verdix Agent",
    targetDataset: "student_data_v2",
    enclaveId: "enclave-org-prod-01",
    status: "SUCCESS",
    details: "Computed summary statistics, quantiles, and fairness disparities locally across 142,000 records.",
    sha256Proof: "0x12fe...98d4",
  },
  {
    id: "aud-1091",
    timestamp: "2026-09-16 15:42:24 UTC",
    event: "Dataset evaluated locally",
    actor: "Evaluation Engine",
    targetDataset: "student_data_v2",
    enclaveId: "enclave-org-prod-01",
    status: "INFO",
    details: "Pandas dataframe loaded in private RAM enclave. Memory footprint: 184MB. Disk writes: 0.",
    sha256Proof: "0x98ca...33b1",
  },
  {
    id: "aud-1090",
    timestamp: "2026-09-16 14:10:19 UTC",
    event: "Raw-data export blocked",
    actor: "Privacy Guardrail",
    targetDataset: "customer_data",
    enclaveId: "enclave-org-prod-01",
    status: "BLOCKED",
    details:
      "Blocked attempt: Query requested row-level identifiers for sample export. Blocked by policy invariant: prohibitExportOfRawRows=True.",
    sha256Proof: "0xcc44...719b",
  },
  {
    id: "aud-1089",
    timestamp: "2026-09-16 12:00:00 UTC",
    event: "Agent connected",
    actor: "Verdix Agent Daemon",
    targetDataset: "System Enclave",
    enclaveId: "enclave-org-prod-01",
    status: "SUCCESS",
    details: "Mutual TLS handshake verified. Agent v0.1.0 authenticated and enrolled in US-East Enclave.",
    sha256Proof: "0x4a12...89ee",
  },
  {
    id: "aud-1088",
    timestamp: "2026-09-15 11:20:45 UTC",
    event: "Protected metrics generated",
    actor: "Verdix Agent",
    targetDataset: "student_survey",
    enclaveId: "enclave-org-prod-01",
    status: "SUCCESS",
    details: "Generated 18 categorical histograms with Laplace noise added (epsilon=0.5).",
    sha256Proof: "0xfa77...2110",
  },
  {
    id: "aud-1087",
    timestamp: "2026-09-14 18:05:12 UTC",
    event: "Raw-data export blocked",
    actor: "Privacy Guardrail",
    targetDataset: "customer_data",
    enclaveId: "enclave-org-prod-01",
    status: "BLOCKED",
    details:
      "Blocked attempt: Bucket size below minimum k-anonymity threshold (n=4 < k=10). Group suppressed by privacy engine.",
    sha256Proof: "0x99dd...003a",
  },
];
